# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Keran Tai
email: taikeran@gmail.com
description: |+
 Active looking for jobs :) 
 Front/End/Full stack/Mobile/Machaine Learning/Big Data
 OR 
 If you need a personal trainer (CIF/Webber Goodlife) 
 You can also contact me throught my email. I have been workout for over 2 years and 
 making good progress with strong knowledge on weight losing/body building. Rate: $30/h 
 BP: 225*2/ DL:205*6/ Squat:225*4 

baseurl: "" # the subpath of your site, e.g. /blog
url: "www.taikeran.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: davidtai111
github_username:  DavidTai1

# Build settings
markdown: kramdown
theme: minima
plugins:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
